# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/bindings.conf
source = $HOME/.config/hypr/media.conf
source = $HOME/.config/hypr/looknfeel.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/envs.conf
source = $HOME/.config/hypr/windows.conf
source = $HOME/.config/hypr/colors.conf
