general {
    lock_cmd = pidof hyprlock || hyprlock                    # launch hyprlock if not already running
    before_sleep_cmd = loginctl lock-session                 # lock before suspend
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on && systemctl --user restart pipewire pipewire-pulse wireplumber  # turn on display + restart audio
    inhibit_sleep = 3                                        # wait until screen is locked
}

listener {
    timeout = 450                                            # 7m30s — lock screen
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600                                            # 10min — screen off
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
