--ozone-platform=wayland
--enable-wayland-ime
--enable-features=WebRTCPipeWireCapturer,PipeWireScreenCast,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder
--disable-features=UseChromeOSDirectVideoDecoder
--ignore-gpu-blocklist
