--ozone-platform=wayland
--enable-wayland-ime
--enable-features=WebRTCPipeWireCapturer,PipeWireScreenCast,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder,WaylandFractionalScaleV1,WaylandPerSurfaceScale
--disable-features=UseChromeOSDirectVideoDecoder
--ignore-gpu-blocklist
