monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_01_00.1"
      }
    ]
    actions = {
      update-props = {
        priority.session = 100
        priority.driver = 100
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.pci-0000_01_00.1.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 100
        priority.driver = 100
      }
    }
  }
]
